### PR TITLE
fix: Do not toggle dropwdown on pill removal

### LINKED ISSUE #134: Toggle dropdown visibility on click remove tag
In this example - https://dowjones.github.io/react-dropdown-tree-select/#/story/basic-no-extra-styles
If you clicked on X tag, it's toggle dropdown visibility. But in other example all works correctly.

Thx!

### PR DESCRIPTION
**Pull request by priyanshu92**
Fixes #134 

Prevents the dropdown from toggling again and again when the selected tags are removed.

### CODE REVIEW

File: src/tag/index.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ class Tag extends PureComponent {
     return (
       <span className={cx('tag')}>
         {label}
-        <button onClick={this.handleClick} className={cx('tag-remove')} type="button">
+        <button onClick={e => this.handleClick(e)} className={cx('tag-remove')} type="button">
```
Comment (mrchief) [inline src/tag/index.js]: This can be simply `onClick={this.handleClick}` (avoids creating a function on every render). I wonder why linting didn't flag this.

File: src/tag/index.js [hunk 2]
```diff
@@ -13,9 +13,9 @@ class Tag extends PureComponent {
     onDelete: PropTypes.func
   }
 
-  handleClick = () => {
+  handleClick = e => {
     const { id, onDelete } = this.props
-
+    e.stopPropagation()
```
Comment (mrchief) [inline src/tag/index.js]: Don't remember why but I think we also need to add `e.stopImmediatePropagation()` too.

File: src/tag/index.js (hunk 1 above)
Comment (priyanshu92) [reply src/tag/index.js]: Okay. I'll update it.

File: src/tag/index.js (hunk 2 above)
Comment (priyanshu92) [reply src/tag/index.js]: Right. We can use `stopImmediatePropagation()` because it implicitly calls `stopPropagation()`. I'll update the code.
